#!/bin/bash

# Quick Start Guide for Financial Tools Django Site

echo "╔════════════════════════════════════════════════════════════╗"
echo "║   💰 Financial Tools - Django Web Application 💰          ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Step 1: Navigate to project
echo "📁 Step 1: Opening project directory..."
cd "/Users/shazibsiddique/Desktop/ai capstone project "

# Step 2: Activate virtual environment
echo "🐍 Step 2: Activating virtual environment..."
source .venv/bin/activate

# Step 3: Show what's running
echo ""
echo "✅ Virtual environment activated"
echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║                   QUICK START GUIDE                        ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "🚀 To start the Django server, run:"
echo ""
echo "   python manage.py runserver"
echo ""
echo "Then open your browser to:"
echo ""
echo "   http://localhost:8000"
echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║                   FEATURES AVAILABLE                       ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "🏠 HOME PAGE (http://localhost:8000/)"
echo "   - Landing page with feature overview"
echo "   - Quick links to all tools"
echo ""
echo "💬 AI CHATBOT (http://localhost:8000/chatbot/)"
echo "   - Ask any financial question"
echo "   - Get personalized AI-powered advice"
echo "   - Example: 'What is compound interest?'"
echo ""
echo "📊 BUDGET CALCULATOR (http://localhost:8000/budget/)"
echo "   - Plan your finances with 50/30/20 method"
echo "   - Customize budget percentages"
echo "   - See detailed breakdown"
echo ""
echo "🧮 FINANCIAL CALCULATOR (http://localhost:8000/calculator/)"
echo "   - Compound Interest Calculator"
echo "   - Loan Payment Calculator"
echo "   - Investment Growth Calculator"
echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║                   IMPORTANT NOTES                          ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "⚠️  Make sure Ollama is running before using the chatbot:"
echo ""
echo "    In a new terminal, run: ollama serve"
echo ""
echo "💾 Financial data loaded: 5,818 records"
echo "📦 Vector database: ./chrome_langchain_db/"
echo ""
echo "═════════════════════════════════════════════════════════════"
echo ""
